baseURL = "http://example.org/"
languageCode = "en-us"
theme = "trailblazer"
title = "Kwat"
googleAnalytics = ""
paginate = 8

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true

[related]
threshold = 0
includeNewer = true
toLower = false

[[related.indices]]
name = "categories"
weight = 100

[[related.indices]]
name = "date"
weight = 10

[params]
author = "Kwat Medetgul-Ernar"
description = "Website of Kwat Medetgul-Ernar"

[[menu.main]]
name = "About"
url = "/about"

[[menu.main]]
name = "Posts"
url = "/posts"

[[menu.main]]
name = "Topics"
url = "/categories"

[[menu.social]]
name = "GitHub"
url = "https://github.com/KwatME"
pre = "<i class='fab fa-github'></i>"

[[menu.social]]
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=PAM4lScAAAAJ&hl"
pre = "<i class='ai ai-google-scholar ai-lg'></i>"

[[menu.social]]
name = "Podcast"
url = "https://anchor.fm/kwat"
pre = "<i class='fa fa-podcast'></i>"

[[menu.social]]
name = "YouTube"
url = "https://www.youtube.com/channel/UCYDeuExg0JHfKj4CfjQ260A"
pre = "<i class='fab fa-youtube'></i>"

[[menu.social]]
name = "Twitter"
url = "https://twitter.com/KwatME"
pre = "<i class='fab fa-twitter'></i>"

[[menu.social]]
name = "Instagram"
url = "https://www.instagram.com/kwat.me"
pre = "<i class='fab fa-instagram'></i>"

[[menu.social]]
name = "Zoom"
url = "https://stanford.zoom.us/my/kwatme?pwd=Q2dzVXUwdmhuZzg2Vkc4aFliSFFnQT09"
pre = "<i class='fa fa-phone'></i>"
